### ISSUE TITLE
Java support policy

### ISSUE THREAD

**Issue by sobolewskikamil** [SabreOSS/yare#66]
Currently we are supporting JDK in versions 8, 9, 10, 11 and 12. The number of build pipelines is constantly growing and applying changes is more and more troublesome. My proposition is to support only LTS (Long Term Support) versions of Java platform and the newest versions released after the last LTS. This way supporting next LTS version will be much easier. So for now we would have build pipelines for JDK 8, 11 and 12. What do you think?

**Comment by MarcinLachowicz** [comment]
Brilliant idea, I vote for :)

**Comment by krzysztofreczek** [comment]
+1
